### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by avkhozov** [gvengel/exim_exporter#6]
Do you have any plans for develop `Dockerfile` for exporter and upload image to `hub.docker.com`? It would be nice. Are PR would be welcome?

**Comment by gvengel** [comment]
Hey @avkhozov! 😄 

I actually began development of the project via docker, but ended up switching to vagrant for a number of reasons. Since I wasn't actively using it, I later discovered a couple of issues with the `Dockerfile`. At that point I decided it was better to just delete the file, rather than leave it broken, since I didn't think anyone was using it.

As you are interested, and I'm sure others would be too, I'd be happy to resurrect docker support. Most of the work will actually be getting CI/CD setup to publish to Docker Hub. I'll try to find some time this weekend. 

Of course, if you are keen, PR's are always welcome.

**Comment by gvengel** [comment]
Okay, I think everything should be working with version 1.3.0. Let me know if you run into any issues. 

I added a few notes at the bottom of the [readme](https://github.com/gvengel/exim_exporter/blob/master/README.md), but I don't actually run docker in production, so feel free to send me some pointers, or a PR with changes.

**Comment by avkhozov** [comment]
Thank you so much, I will test it soon.

**Comment by avkhozov** [comment]
Thank you again, everything looks good in my environment.
